# fly.toml app configuration file generated for crowdfunding-back-end-lrp on 2024-01-20T12:54:17+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crowdfunding-back-end-lrp"
primary_region = "syd"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
